import { PaperPlaneRight, Trash } from '@phosphor-icons/react'
import { useEffect, useState, type FormEvent } from 'react'
import { useAuth } from '../../features/auth/AuthProvider'
import { apiRequest } from '../../lib/api'
import { formatPrice } from '../../lib/format'
import type { Product, User } from '../../types'
import { AdminEmpty, AdminError, AdminPage, Status } from './AdminDashboardPage'

interface AdminUser extends User { isActive: boolean; createdAt: string }
interface Order { _id: string; orderCode: string; user?: { fullName?: string; email?: string }; totalItems: number; totalAmount: number; orderStatus: string; paymentStatus: string; paymentMethod: string; createdAt: string }
interface Conversation { conversationId: string; lastMessage: string; updatedAt: string; unreadCount: number; sender?: { fullName?: string }; senderRole: string }
interface Message { _id: string; senderName: string; senderRole: string; message: string; createdAt: string }
interface MonthlyRevenue { _id: number; revenue: number }
interface Distribution { status?: string; method?: string; count: number; total?: number }

function useAdminData<T>(path: string) {
  const { token } = useAuth(); const [data, setData] = useState<T | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  async function load() { if (!token) return; setLoading(true); setError(''); try { setData((await apiRequest<{ data: T }>(path, {}, token)).data) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load data.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [path, token]) // eslint-disable-line react-hooks/exhaustive-deps
  return { data, loading, error, setError, load }
}

export function AdminUsersPage() {
  const { token, user: currentUser } = useAuth(); const state = useAdminData<AdminUser[]>('/users'); const [search, setSearch] = useState('')
  const users = (state.data || []).filter((user) => `${user.fullName} ${user.email}`.toLowerCase().includes(search.toLowerCase()))
  async function patch(id: string, kind: 'role' | 'status', role?: string) { if (!token) return; try { await apiRequest(`/users/${id}/${kind}`, { method: 'PATCH', body: kind === 'role' ? JSON.stringify({ role }) : undefined }, token); await state.load() } catch (reason) { state.setError(reason instanceof Error ? reason.message : 'Could not update user.') } }
  return <AdminPage title="Users" description="Control staff roles and customer account access."><div className="admin-toolbar"><input placeholder="Search name or email" aria-label="Search users" value={search} onChange={(event) => setSearch(event.target.value)} /><span>{users.length} users</span></div>{state.error && <AdminError message={state.error} />}<section className="admin-panel"><div className="admin-table-wrap"><table><thead><tr><th>User</th><th>Phone</th><th>Role</th><th>Status</th><th>Joined</th><th /></tr></thead><tbody>{users.map((user) => <tr key={user._id}><td><strong>{user.fullName}</strong><small>{user.email}</small></td><td>{user.phone || '-'}</td><td><select aria-label={`Role for ${user.fullName}`} value={user.role} disabled={user._id === currentUser?._id} onChange={(event) => void patch(user._id, 'role', event.target.value)}><option value="user">User</option><option value="admin">Admin</option></select></td><td><Status value={user.isActive} /></td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td><button className="admin-table-action" disabled={user._id === currentUser?._id} onClick={() => void patch(user._id, 'status')}>{user.isActive ? 'Disable' : 'Enable'}</button></td></tr>)}</tbody></table></div>{!state.loading && !users.length && <AdminEmpty message="No users found." />}</section></AdminPage>
}

export function AdminOrdersPage() {
  const { token } = useAuth(); const state = useAdminData<Order[]>('/orders/admin/all'); const [filter, setFilter] = useState('all'); const statuses = ['pending','confirmed','processing','shipped','delivered','completed','cancelled','returned']; const orders = (state.data || []).filter((order) => filter === 'all' || order.orderStatus === filter)
  async function update(id: string, orderStatus: string) { if (!token) return; try { await apiRequest(`/orders/${id}/status`, { method: 'PUT', body: JSON.stringify({ orderStatus }) }, token); await state.load() } catch (reason) { state.setError(reason instanceof Error ? reason.message : 'Could not update order.') } }
  async function remove(id: string) { if (!token || !confirm('Permanently delete this order? Inventory may be restored.')) return; try { await apiRequest(`/orders/${id}`, { method: 'DELETE' }, token); await state.load() } catch (reason) { state.setError(reason instanceof Error ? reason.message : 'Could not delete order.') } }
  return <AdminPage title="Orders" description="Track fulfillment, payment, and order lifecycle."><div className="admin-toolbar"><select aria-label="Filter order status" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All statuses</option>{statuses.map((status) => <option key={status}>{status}</option>)}</select><span>{orders.length} orders</span></div>{state.error && <AdminError message={state.error} />}<section className="admin-panel"><div className="admin-table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Payment</th><th>Items</th><th>Total</th><th>Status</th><th /></tr></thead><tbody>{orders.map((order) => <tr key={order._id}><td><strong>{order.orderCode}</strong><small>{new Date(order.createdAt).toLocaleDateString()}</small></td><td>{order.user?.fullName || 'Customer'}<small>{order.user?.email}</small></td><td>{order.paymentMethod.toUpperCase()}<small>{order.paymentStatus}</small></td><td>{order.totalItems}</td><td>{formatPrice(order.totalAmount)}</td><td><select aria-label={`Status for ${order.orderCode}`} value={order.orderStatus} onChange={(event) => void update(order._id, event.target.value)}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></td><td><button className="admin-icon-danger" aria-label="Delete order" onClick={() => void remove(order._id)}><Trash size={18} /></button></td></tr>)}</tbody></table></div>{!state.loading && !orders.length && <AdminEmpty message="No orders found." />}</section></AdminPage>
}

export function AdminChatsPage() {
  const { token } = useAuth(); const conversations = useAdminData<Conversation[]>('/chats/conversations'); const [active, setActive] = useState(''); const [messages, setMessages] = useState<Message[]>([]); const [error, setError] = useState('')
  const selected = conversations.data?.find((item) => item.conversationId === active)
  useEffect(() => { if (!token || !active) return; apiRequest<{ data: Message[] }>(`/chats/${active}/messages`, {}, token).then((response) => setMessages(response.data)).catch((reason: Error) => setError(reason.message)) }, [active, token])
  async function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token || !active) return; const form = event.currentTarget; const message = String(new FormData(form).get('message') || '').trim(); if (!message) return; try { const response = await apiRequest<{ data: Message }>(`/chats/${active}/send`, { method: 'POST', body: JSON.stringify({ message }) }, token); setMessages((current) => [...current, response.data]); form.reset(); await conversations.load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not send message.') } }
  return <AdminPage title="Customer chat" description="Review conversations and reply to support requests.">{(conversations.error || error) && <AdminError message={conversations.error || error} />}<section className="admin-chat"><aside>{conversations.data?.map((item) => <button className={active === item.conversationId ? 'active' : ''} key={item.conversationId} onClick={() => setActive(item.conversationId)}><strong>{item.sender?.fullName || `Customer ${item.conversationId.slice(-5)}`}</strong><span>{item.lastMessage}</span>{item.unreadCount > 0 && <b>{item.unreadCount}</b>}</button>)}{!conversations.loading && !conversations.data?.length && <AdminEmpty message="No conversations yet." />}</aside><div className="admin-thread">{active ? <><header><strong>{selected?.sender?.fullName || 'Customer conversation'}</strong><span>Support thread</span></header><div className="admin-messages">{messages.map((message) => <article className={message.senderRole === 'admin' ? 'is-admin' : ''} key={message._id}><strong>{message.senderName}</strong><p>{message.message}</p><time>{new Date(message.createdAt).toLocaleString()}</time></article>)}</div><form onSubmit={send}><input name="message" aria-label="Reply" placeholder="Write a reply" autoComplete="off" /><button aria-label="Send reply"><PaperPlaneRight size={20} /></button></form></> : <AdminEmpty message="Select a conversation." />}</div></section></AdminPage>
}

export function AdminAnalyticsPage() {
  const year = new Date().getFullYear(); const revenue = useAdminData<MonthlyRevenue[]>(`/dashboard/revenue/monthly?year=${year}`); const status = useAdminData<Distribution[]>('/dashboard/orders/status-distribution'); const payments = useAdminData<Distribution[]>('/dashboard/payments/method-distribution'); const products = useAdminData<Product[]>('/dashboard/products/top-selling?limit=8')
  const max = Math.max(...(revenue.data || []).map((item) => item.revenue), 1); const errors = revenue.error || status.error || payments.error || products.error
  return <AdminPage title="Analytics" description={`Revenue and commerce signals for ${year}.`}>{errors && <AdminError message={errors} />}<section className="admin-analytics-grid"><article className="admin-panel admin-chart"><h2>Monthly revenue</h2><div className="admin-bars">{Array.from({ length: 12 }, (_, index) => { const value = revenue.data?.find((item) => item._id === index + 1)?.revenue || 0; return <div key={index}><span style={{ height: `${Math.max(value ? 6 : 1, value / max * 100)}%` }} title={formatPrice(value)} /><small>{index + 1}</small></div> })}</div></article><article className="admin-panel"><h2>Order status</h2><div className="admin-breakdown">{status.data?.map((item) => <div key={item.status}><Status value={item.status || ''} /><strong>{item.count}</strong></div>)}</div></article><article className="admin-panel"><h2>Payment methods</h2><div className="admin-breakdown">{payments.data?.map((item) => <div key={item.method}><span>{item.method?.toUpperCase()}</span><strong>{item.count} · {formatPrice(item.total || 0)}</strong></div>)}</div></article><article className="admin-panel"><h2>Top products</h2><div className="admin-breakdown">{products.data?.map((product) => <div key={product._id}><span>{product.name}</span><strong>{product.stock} stock</strong></div>)}</div></article></section></AdminPage>
}
